[package]
name = "simple-web-browser"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "swb"
path = "src/main.rs"

[dependencies]
gtk = "0.15.4"
cascade = "1.0.0"
dlopen = "0.1.8"
dlopen_derive = "0.1.4"
