[package]
name = "swb_webkit"
version = "22.225.1"
edition = "2021"

[dependencies]
webkit2gtk = "0.17.1"
gtk = "0.15.4"

[lib]
name = "swb_webkit"
crate-type = [ "cdylib" ]
path = "src/swb_webkit.rs"
